### ISSUE TITLE
Scene does not load/play on mobile

### ISSUE THREAD

**Issue by cvan** [aframevr/360-image-gallery-boilerplate#4]
**Description:**

1. Load https://aframe.io/examples/showcase/360-image-gallery/ (or https://aframe.io/360-image-gallery-boilerplate/) on mobile.
2. Notice the screen is black.
3. I haven't looked, but is this a video codec issue or just not listening for a [user-gesture requirement in Chrome to explicitly play the video](https://aframe.io/docs/0.3.0/introduction/faq.html#why-does-my-video-not-play-on-mobile)? If so, we should probably fix the [360-image-gallery-boilarplate](https://github.com/aframevr/360-image-gallery-boilerplate) to handle that (with [this great walkthrough](http://stackoverflow.com/questions/38380912/why-is-my-video-or-videosphere-not-playing-on-mobile-in-a-frame-vr/38380941#38380941)).

- A-Frame Version: `0.3.2`
- Platform/Device: Chrome for Android
- Reproducible Code Snippet or Demo URL [highly encouraged]: https://aframe.io/360-image-gallery-boilerplate/

**Comment by onim4ru** [comment]
Hi ! Thanks for the request. 

https://aframe.io/examples/showcase/videosphere/ doesnt seems to function too in Android Chrome and Iphone's Safari and Chrome.

Error in  Chrome/iphone's Chrome is : Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture // .play function

------------------ edit 08.11.2016
When you launch the event play() by clicking on the google glasses (custom made) the video is launching and after you can trigger onClick() events attached to images for examples.

Iphone : Safari / Chrome
Event is launched but video isnt. It is opened by the iphone player if you PIN the website to the home screen so you have on one side your scene and interactivity and another you have your video playing endlessly in your player. 

Is it possible to make the videosphere working in Iphone as in others ?

**Comment by ngokevin** [comment]
This repository has no video. For the video example, refer to http://stackoverflow.com/questions/38380912/why-is-my-video-or-videosphere-not-playing-on-mobile-in-a-frame-vr
